### ISSUE TITLE
Example using version 2.0

### ISSUE THREAD

**Issue by karlclement** [TheFrozenFire/PHP-Swagger-Parser#7]
Hi there,

First off, great work. 

Could you provide an example using your 2.0 version? I am currently instantiating a Document object, but it requires a Document object in constructor. How would you use this library to analyze and parse a hosted or local swagger.json file?

I am trying to use this library to parse my schema to showcase it in some custom documentation.

Could you possibly paste an example? Thank you,

**Comment by TheFrozenFire** [comment]
Hey Karl,

Sorry for the lack of documentation. That's one of my next tasks once I get the underlying project I'm using to do this work finished. :)

What the constructor of any `Swagger\Object` wants is an stdClass object that is produced by json_decode(). So as an example:

``` php
$spec = file_get_contents('http://petstore.swagger.io/v2/swagger.json');
$decodedSpec = json_decode($spec);

$swagger = new Swagger\Document($decodedSpec);

var_dump($swagger->getOperationById('updatePet'));
```

**Comment by TheFrozenFire** [comment]
I've added a bit more documentation to the new README. I'm going to hold off on writing more comprehensive documentation, as I still need to polish up the generic Swagger client that goes with this. I'll probably need to change some interfaces as I do that.

Hopefully what I've added sheds some light on the use.

**Comment by karlclement** [comment]
Amazing. Thank you @TheFrozenFire
